#!/usr/bin/with-contenv bash

s6-setuidgid registry exec reg server \
    --interval 1h0m0s \
    --listen-address 0.0.0.0 \
    --port 5001 \
    -u ${REG_USER} \
    -p ${REG_PASS} \
    --asset-path ${REG_ASSET_PATH} \
    --registry ${REGISTRY_HTTP_HOST} \
    --cert ${REGISTRY_HTTP_TLS_CERTIFICATE} \
    --key ${REGISTRY_HTTP_TLS_KEY}



