#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

REG_ASSET_PATH="${REG_ASSET_PATH:-/data/web}";

vecho "Ensure webui asset directories exist.";
mkdir -p \
    ${REG_ASSET_PATH} \
    ;

if [ -z "${REGISTRY_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown -R ${S6_USER:-alpine}:${PGID:-1000} \
        ${REG_ASSET_PATH} \
        ;
fi;
