#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

REG_ASSET_PATH="${REG_ASSET_PATH:-/data/web}";

vecho "Ensure webui asset directories exist.";
mkdir -p \
    ${REG_ASSET_PATH} \
    ;

vecho "Fixing permissions.";
chown -R ${S6_USER:-alpine}:${S6_USER:-alpine} \
    ${REG_ASSET_PATH} \
    ;
