#!/usr/bin/with-contenv bash

# make sure we have certs
if [ -f ${REGISTRY_HTTP_TLS_KEY} ] && [ -f ${REGISTRY_HTTP_TLS_CERTIFICATE} ]; then
    echo "using certificate found in ${REGISTRY_HTTP_TLS_KEY}"
else
    SUBJECT="/C=US/ST=NY/L=EXAMPLE/O=EXAMPLE/OU=REGISTRY/CN=localhost/emailAddress=everybodycanseethis@mailinator.com"
    SSLSUBJECT=${SSLSUBJECT:-$SUBJECT};
    echo "generating self-signed certificate in ${REGISTRY_HTTP_TLS_KEY}, you can replace these with your own keys if required";
    s6-setuidgid ${PUID}:${PGID} openssl req -newkey rsa:4096 -x509 -days 3650 -nodes -out ${REGISTRY_HTTP_TLS_CERTIFICATE} -keyout ${REGISTRY_HTTP_TLS_KEY} -subj "${SSLSUBJECT}";
fi

# trust said certificate
cp ${REGISTRY_HTTP_TLS_CERTIFICATE} /etc/ssl/certs/ \
    && update-ca-certificates

# make sure we have basic auth at the least
if [ -f ${REGISTRY_AUTH_HTPASSWD_PATH} ];
then
    echo "using credentials found in ${REGISTRY_AUTH_HTPASSWD_PATH}";
else
    echo "generatign authentication in ${REGISTRY_AUTH_HTPASSWD_PATH}";
    echo "adding credentials for: ${REG_USER}";
    s6-setuidgid ${PUID}:${PGID} htpasswd -bcB ${REGISTRY_AUTH_HTPASSWD_PATH} ${REG_USER} ${REG_PASS}
fi;

